#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:
# this will start the new jenkins docker container, and will use a volume from /var/lib/jenkins to
# /var/jenkins_home in the container.  This way your settings and plugins are saved in the host
# volume
docker run -d -v /var/lib/jenkins:/var/jenkins_home -p 8080:8080 -p 50000:50000 --restart=on-failure c
ustom-jenkins-docker
